project:
  type: website
  output-dir: docs

website:
  title: "My Website"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: multi-os-network.qmd
        text: Multi-OS-Network
      - href: commandline_histories.qmd
        text: Commandline-Histories

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show the code!"

