project:
  type: website
  output-dir: docs

website:
  title: "Amelia's Projects"

  navbar:
    left:
      - href: multi-os_network.qmd
        text: Multi-OS Network
      - href: command-line_history.qmd
        text: Command-Line History

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show the code!"

